app:
  name: bff
  image:
    repository: "onecx/onecx-announcement-bff"
  operator:
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          announcement:
            read: permission on all GET requests and POST search including assigned meta data
            write: permission on PUT, POST, PATCH requests, where objects are saved or updated
            delete: permission on all DELETE requests
          product:
            read: permission to read available products/applications
          workspace:
            read: permission to read available workspaces
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-an:all, ocx-ws:read, ocx-pm:read, ocx-ps:read ]